#pragma once

#include <nvperf_host.h>
#include <nvperf_cuda_host.h>
#include <map>
#include <stdlib.h>
#include <string>
#include <vector>
#include <unordered_map>
using namespace std;

struct ctxProfilerData;

#define CODE_MAP_MIN_KEY 1000
#define CODE_MAP_MAX_KEY 1129
namespace Metrics{
	typedef std::map<int, string> metricList;

	metricList get_metricList();// create sample metric list
	
	static unordered_map<string, string> _metricToPWFormula = {
		{"achieved_occupancy", "sm__warps_active.avg.pct_of_peak_sustained_active"},
		{"branch_efficiency", "smsp__sass_average_branch_targets_threads_uniform.pct"},
		{"cf_executed", "smsp__inst_executed_pipe_cbu.sum"},
		{"double_precision_fu_utilization", "smsp__inst_executed_pipe_fp64.avg.pct_of_peak_sustained_active"},
		{"dram_read_bytes", "dram__bytes_read.sum"},
		{"dram_read_throughput", "dram__bytes_read.sum.per_second"},
		{"dram_read_transactions", "dram__sectors_read.sum"},
		{"dram_utilization", "dram__throughput.avg.pct_of_peak_sustained_elapsed"},
		{"dram_write_bytes", "dram__bytes_write.sum"},
		{"dram_write_throughput", "dram__bytes_write.sum.per_second"},
		{"dram_write_transactions", "dram__sectors_write.sum"},
		{"eligible_warps_per_cycle", "smsp__warps_eligible.sum.per_cycle_active"},
		{"flop_count_dp_add", "smsp__sass_thread_inst_executed_op_dadd_pred_on.sum"},
		{"flop_count_dp_fma", "smsp__sass_thread_inst_executed_op_dfma_pred_on.sum"},
		{"flop_count_dp_mul", "smsp__sass_thread_inst_executed_op_dmul_pred_on.sum"},
		{"flop_count_hp_add", "smsp__sass_thread_inst_executed_op_hadd_pred_on.sum"},
		{"flop_count_hp_fma", "smsp__sass_thread_inst_executed_op_hfma_pred_on.sum"},
		{"flop_count_hp_mul", "smsp__sass_thread_inst_executed_op_hmul_pred_on.sum"},
		{"flop_count_sp_add", "smsp__sass_thread_inst_executed_op_fadd_pred_on.sum"},
		{"flop_count_sp_fma", "smsp__sass_thread_inst_executed_op_ffma_pred_on.sum"},
		{"flop_count_sp_mul", "smsp__sass_thread_inst_executed_op_fmul_pred_on.sum"},
		{"flop_dp_efficiency", "smsp__sass_thread_inst_executed_ops_dadd_dmul_dfma_pred_on.avg.pct_of_peak_sustained_elapsed"},
		{"flop_hp_efficiency", "smsp__sass_thread_inst_executed_ops_hadd_hmul_hfma_pred_on.avg.pct_of_peak_sustained_elapsed"},
		{"flop_sp_efficiency", "smsp__sass_thread_inst_executed_ops_fadd_fmul_ffma_pred_on.avg.pct_of_peak_sustained_elapsed"},
		{"gld_efficiency", "smsp__sass_average_data_bytes_per_sector_mem_global_op_ld.pct"},
		{"gld_throughput", "l1tex__t_bytes_pipe_lsu_mem_global_op_ld.sum.per_second"},
		{"gld_transactions", "l1tex__t_sectors_pipe_lsu_mem_global_op_ld.sum"},
		{"gld_transactions_per_request", "l1tex__average_t_sectors_per_request_pipe_lsu_mem_global_op_ld.ratio"},
		{"global_atomic_requests", "l1tex__t_requests_pipe_lsu_mem_global_op_atom.sum"},
		{"global_load_requests", "l1tex__t_requests_pipe_lsu_mem_global_op_ld.sum"},
		{"global_reduction_requests", "l1tex__t_requests_pipe_lsu_mem_global_op_red.sum"},
		{"global_store_requests", "l1tex__t_requests_pipe_lsu_mem_global_op_st.sum"},
		{"gst_efficiency", "smsp__sass_average_data_bytes_per_sector_mem_global_op_st.pct"},
		{"gst_throughput", "l1tex__t_bytes_pipe_lsu_mem_global_op_st.sum.per_second"},
		{"gst_transactions", "l1tex__t_bytes_pipe_lsu_mem_global_op_st.sum"},
		{"gst_transactions_per_request", "l1tex__average_t_sectors_per_request_pipe_lsu_mem_global_op_st.ratio"},
		{"half_precision_fu_utilization", "smsp__inst_executed_pipe_fp16.avg.pct_of_peak_sustained_active"},
		{"inst_bit_convert", "smsp__sass_thread_inst_executed_op_conversion_pred_on.sum"},
		{"inst_compute_ld_st", "smsp__sass_thread_inst_executed_op_memory_pred_on.sum"},
		{"inst_control", "smsp__sass_thread_inst_executed_op_control_pred_on.sum"},
		{"inst_executed", "smsp__inst_executed.sum"},
		{"inst_executed_global_atomics", "smsp__sass_inst_executed_op_global_atom.sum"},
		{"inst_executed_global_loads", "smsp__inst_executed_op_global_ld.sum"},
		{"inst_executed_global_reductions", "smsp__inst_executed_op_global_red.sum"},
		{"inst_executed_global_stores", "smsp__inst_executed_op_global_st.sum"},
		{"inst_executed_local_loads", "smsp__inst_executed_op_local_ld.sum"},
		{"inst_executed_local_stores", "smsp__inst_executed_op_local_st.sum"},
		{"inst_executed_shared_loads", "smsp__inst_executed_op_shared_ld.sum"},
		{"inst_executed_shared_stores", "smsp__inst_executed_op_shared_st.sum"},
		{"inst_executed_surface_atomics", "smsp__inst_executed_op_surface_atom.sum"},
		{"inst_executed_surface_reductions", "smsp__inst_executed_op_surface_red.sum"},
		{"inst_executed_surface_stores", "smsp__inst_executed_op_surface_st.sum"},
		{"inst_executed_tex_ops", "smsp__inst_executed_op_texture.sum"},
		{"inst_fp_16", "smsp__sass_thread_inst_executed_op_fp16_pred_on.sum"},
		{"inst_fp_32", "smsp__sass_thread_inst_executed_op_fp32_pred_on.sum"},
		{"inst_fp_64", "smsp__sass_thread_inst_executed_op_fp64_pred_on.sum"},
		{"inst_integer", "smsp__sass_thread_inst_executed_op_integer_pred_on.sum"},
		{"inst_inter_thread_communication", "smsp__sass_thread_inst_executed_op_inter_thread_communication_pred_on.sum"},
		{"inst_issued", "smsp__inst_issued.sum"},
		{"inst_misc", "smsp__sass_thread_inst_executed_op_misc_pred_on.sum"},
		{"inst_per_warp", "smsp__average_inst_executed_per_warp.ratio"},
		{"ipc", "smsp__inst_executed.avg.per_cycle_active"},
		{"issue_slot_utilization", "smsp__issue_active.avg.pct_of_peak_sustained_active"},
		{"issue_slots", "smsp__inst_issued.sum"},
		{"issued_ipc", "smsp__inst_issued.avg.per_cycle_active"},
		{"l1_sm_lg_utilization", "l1tex__lsu_writeback_active.avg.pct_of_peak_sustained_active"},
		{"l2_atomic_throughput", "lts__t_sectors_srcunit_l1_op_atom.sum.per_second"},
		{"l2_atomic_transactions", "lts__t_sectors_srcunit_l1_op_atom.sum"},
		{"l2_global_atomic_store_bytes", "lts__t_bytes_equiv_l1sectormiss_pipe_lsu_mem_global_op_atom.sum"},
		{"l2_global_load_bytes", "lts__t_bytes_equiv_l1sectormiss_pipe_lsu_mem_global_op_ld.sum"},
		{"l2_local_load_bytes", "lts__t_bytes_equiv_l1sectormiss_pipe_lsu_mem_local_op_ld.sum"},
		{"l2_read_throughput", "lts__t_sectors_op_read.sum.per_second"},
		{"l2_read_transactions", "lts__t_sectors_op_read.sum"},
		{"l2_surface_load_bytes", "lts__t_bytes_equiv_l1sectormiss_pipe_tex_mem_surface_op_ld.sum"},
		{"l2_surface_store_bytes", "lts__t_bytes_equiv_l1sectormiss_pipe_tex_mem_surface_op_st.sum"},
		{"l2_tex_hit_rate", "lts__t_sector_hit_rate.pct"},
		{"l2_tex_read_hit_rate", "lts__t_sector_op_read_hit_rate.pct"},
		{"l2_tex_read_throughput", "lts__t_sectors_srcunit_tex_op_read.sum.per_second"},
		{"l2_tex_read_transactions", "lts__t_sectors_srcunit_tex_op_read.sum"},
		{"l2_tex_write_hit_rate", "lts__t_sector_op_write_hit_rate.pct"},
		{"l2_tex_write_throughput", "lts__t_sectors_srcunit_tex_op_read.sum.per_second"},
		{"l2_tex_write_transactions", "lts__t_sectors_srcunit_tex_op_read.sum"},
		{"l2_utilization", "lts__t_sectors.avg.pct_of_peak_sustained_elapsed"},
		{"l2_write_throughput", "lts__t_sectors_op_write.sum.per_second"},
		{"l2_write_transactions", "lts__t_sectors_op_write.sum"},
		{"ldst_fu_utilization", "smsp__inst_executed_pipe_lsu.avg.pct_of_peak_sustained_active"},
		{"local_load_requests", "l1tex__t_requests_pipe_lsu_mem_local_op_ld.sum"},
		{"local_load_throughput", "l1tex__t_bytes_pipe_lsu_mem_local_op_ld.sum.per_second"},
		{"local_load_transactions", "l1tex__t_sectors_pipe_lsu_mem_local_op_ld.sum"},
		{"local_load_transactions_per_request", "l1tex__average_t_sectors_per_request_pipe_lsu_mem_local_op_ld.ratio"},
		{"local_store_requests", "l1tex__t_requests_pipe_lsu_mem_local_op_st.sum"},
		{"local_store_throughput", "l1tex__t_sectors_pipe_lsu_mem_local_op_st.sum.per_second"},
		{"local_store_transactions", "l1tex__t_sectors_pipe_lsu_mem_local_op_st.sum"},
		{"local_store_transactions_per_request", "l1tex__average_t_sectors_per_request_pipe_lsu_mem_local_op_st.ratio"},
		{"pcie_total_data_received", "pcie__read_bytes.sum"},
		{"pcie_total_data_transmitted", "pcie__write_bytes.sum"},
		{"shared_efficiency", "smsp__sass_average_data_bytes_per_wavefront_mem_shared.pct"},
		{"shared_load_throughput", "l1tex__data_pipe_lsu_wavefronts_mem_shared_op_ld.sum.per_second"},
		{"shared_load_transactions", "l1tex__data_pipe_lsu_wavefronts_mem_shared_op_ld.sum"},
		{"shared_store_throughput", "l1tex__data_pipe_lsu_wavefronts_mem_shared_op_st.sum.per_second"},
		{"shared_store_transactions", "l1tex__data_pipe_lsu_wavefronts_mem_shared_op_st.sum"},
		{"shared_utilization", "l1tex__data_pipe_lsu_wavefronts_mem_shared.avg.pct_of_peak_sustained_elapsed"},
		{"single_precision_fu_utilization", "smsp__pipe_fma_cycles_active.avg.pct_of_peak_sustained_active"},
		{"sm_efficiency", "smsp__cycles_active.avg.pct_of_peak_sustained_elapsed"},
		{"sm_tex_utilization", "l1tex__texin_sm2tex_req_cycles_active.avg.pct_of_peak_sustained_elapsed"},
		{"special_fu_utilization", "smsp__inst_executed_pipe_xu.avg.pct_of_peak_sustained_active"},
		{"stall_constant_memory_dependency", "smsp__warp_issue_stalled_imc_miss_per_warp_active.pct"},
		{"stall_inst_fetch", "smsp__warp_issue_stalled_no_instruction_per_warp_active.pct"},
		{"stall_memory_dependency", "smsp__warp_issue_stalled_long_scoreboard_per_warp_active.pct"},
		{"stall_not_selected", "smsp__warp_issue_stalled_not_selected_per_warp_active.pct"},
		{"stall_sleeping", "smsp__warp_issue_stalled_sleeping_per_warp_active.pct"},
		{"stall_texture", "smsp__warp_issue_stalled_tex_throttle_per_warp_active.pct"},
		{"surface_atomic_requests", "l1tex__t_requests_pipe_tex_mem_surface_op_atom.sum"},
		{"surface_load_requests", "l1tex__t_requests_pipe_tex_mem_surface_op_ld.sum"},
		{"surface_reduction_requests", "l1tex__t_requests_pipe_tex_mem_surface_op_red.sum"},
		{"surface_store_requests", "l1tex__t_requests_pipe_tex_mem_surface_op_st.sum"},
		{"sysmem_read_bytes", "lts__t_sectors_aperture_sysmem_op_read*"},
		{"sysmem_read_throughput", "lts__t_sectors_aperture_sysmem_op_read.sum.per_second"},
		{"sysmem_read_transactions", "lts__t_sectors_aperture_sysmem_op_read.sum"},
		{"sysmem_write_bytes", "lts__t_sectors_aperture_sysmem_op_write"},
		{"sysmem_write_throughput", "lts__t_sectors_aperture_sysmem_op_write.sum.per_second"},
		{"sysmem_write_transactions", "lts__t_sectors_aperture_sysmem_op_write.sum"},
		{"tensor_precision_fu_utilization", "sm__pipe_tensor_cycles_active.avg.pct_of_peak_sustained_active"},
		{"tex_cache_hit_rate", "l1tex__t_sector_hit_rate.pct"},
		{"tex_fu_utilization", "smsp__inst_executed_pipe_tex.avg.pct_of_peak_sustained_active"},
		{"tex_sm_tex_utilization", "l1tex__f_tex2sm_cycles_active.avg.pct_of_peak_sustained_elapsed"},
		{"tex_sm_utilization", "sm__mio2rf_writeback_active.avg.pct_of_peak_sustained_elapsed",},
		{"texture_load_requests", "l1tex__t_requests_pipe_tex_mem_texture.sum"},
		{"warp_execution_efficiency", "smsp__thread_inst_executed_per_inst_executed.ratio"},
		{"warp_nonpred_execution_efficiency", "smsp__thread_inst_executed_per_inst_executed.pct"},
	};

	static unordered_map<unsigned int, string> _metricCodeMap = {
		{1000,"achieved_occupancy"},
		{1001,"branch_efficiency"},
		{1002,"cf_executed"},
		{1003,"double_precision_fu_utilization"},
		{1004,"dram_read_bytes"},
		{1005,"dram_read_throughput"},
		{1006,"dram_read_transactions"},
		{1007,"dram_utilization"},
		{1008,"dram_write_bytes"},
		{1009,"dram_write_throughput"},
		{1010,"dram_write_transactions"},
		{1011,"eligible_warps_per_cycle"},
		{1012,"flop_count_dp_add"},
		{1013,"flop_count_dp_fma"},
		{1014,"flop_count_dp_mul"},
		{1015,"flop_count_hp_add"},
		{1016,"flop_count_hp_fma"},
		{1017,"flop_count_hp_mul"},
		{1018,"flop_count_sp_add"},
		{1019,"flop_count_sp_fma"},
		{1020,"flop_count_sp_mul"},
		{1021,"flop_dp_efficiency"},
		{1022,"flop_hp_efficiency"},
		{1023,"flop_sp_efficiency"},
		{1024,"gld_efficiency"},
		{1025,"gld_throughput"},
		{1026,"gld_transactions"},
		{1027,"gld_transactions_per_request"},
		{1028,"global_atomic_requests"},
		{1029,"global_load_requests"},
		{1030,"global_reduction_requests"},
		{1031,"global_store_requests"},
		{1032,"gst_efficiency"},
		{1033,"gst_throughput"},
		{1034,"gst_transactions"},
		{1035,"gst_transactions_per_request"},
		{1036,"half_precision_fu_utilization"},
		{1037,"inst_bit_convert"},
		{1038,"inst_compute_ld_st"},
		{1039,"inst_control"},
		{1040,"inst_executed"},
		{1041,"inst_executed_global_atomics"},
		{1042,"inst_executed_global_loads"},
		{1043,"inst_executed_global_reductions"},
		{1044,"inst_executed_global_stores"},
		{1045,"inst_executed_local_loads"},
		{1046,"inst_executed_local_stores"},
		{1047,"inst_executed_shared_loads"},
		{1048,"inst_executed_shared_stores"},
		{1049,"inst_executed_surface_atomics"},
		{1050,"inst_executed_surface_reductions"},
		{1051,"inst_executed_surface_stores"},
		{1052,"inst_executed_tex_ops"},
		{1053,"inst_fp_16"},
		{1054,"inst_fp_32"},
		{1055,"inst_fp_64"},
		{1056,"inst_integer"},
		{1057,"inst_inter_thread_communication"},
		{1058,"inst_issued"},
		{1059,"inst_misc"},
		{1060,"inst_per_warp"},
		{1061,"ipc"},
		{1062,"issue_slot_utilization"},
		{1063,"issue_slots"},
		{1064,"issued_ipc"},
		{1065,"l1_sm_lg_utilization"},
		{1066,"l2_atomic_throughput"},
		{1067,"l2_atomic_transactions"},
		{1068,"l2_global_atomic_store_bytes"},
		{1069,"l2_global_load_bytes"},
		{1070,"l2_local_load_bytes"},
		{1071,"l2_read_throughput"},
		{1072,"l2_read_transactions"},
		{1073,"l2_surface_load_bytes"},
		{1074,"l2_surface_store_bytes"},
		{1075,"l2_tex_hit_rate"},
		{1076,"l2_tex_read_hit_rate"},
		{1077,"l2_tex_read_throughput"},
		{1078,"l2_tex_read_transactions"},
		{1079,"l2_tex_write_hit_rate"},
		{1080,"l2_tex_write_throughput"},
		{1081,"l2_tex_write_transactions"},
		{1082,"l2_utilization"},
		{1083,"l2_write_throughput"},
		{1084,"l2_write_transactions"},
		{1085,"ldst_fu_utilization"},
		{1086,"local_load_requests"},
		{1087,"local_load_throughput"},
		{1088,"local_load_transactions"},
		{1089,"local_load_transactions_per_request"},
		{1090,"local_store_requests"},
		{1091,"local_store_throughput"},
		{1092,"local_store_transactions"},
		{1093,"local_store_transactions_per_request"},
		{1094,"pcie_total_data_received"},
		{1095,"pcie_total_data_transmitted"},
		{1096,"shared_efficiency"},
		{1097,"shared_load_throughput"},
		{1098,"shared_load_transactions"},
		{1099,"shared_store_throughput"},
		{1100,"shared_store_transactions"},
		{1101,"shared_utilization"},
		{1102,"single_precision_fu_utilization"},
		{1103,"sm_efficiency"},
		{1104,"sm_tex_utilization"},
		{1105,"special_fu_utilization"},
		{1106,"stall_constant_memory_dependency"},
		{1107,"stall_inst_fetch"},
		{1108,"stall_memory_dependency"},
		{1109,"stall_not_selected"},
		{1110,"stall_sleeping"},
		{1111,"stall_texture"},
		{1112,"surface_atomic_requests"},
		{1113,"surface_load_requests"},
		{1114,"surface_reduction_requests"},
		{1115,"surface_store_requests"},
		{1116,"sysmem_read_bytes"},
		{1117,"sysmem_read_throughput"},
		{1118,"sysmem_read_transactions"},
		{1119,"sysmem_write_bytes"},
		{1120,"sysmem_write_throughput"},
		{1121,"sysmem_write_transactions"},
		{1122,"tensor_precision_fu_utilization"},
		{1123,"tex_cache_hit_rate"},
		{1124,"tex_fu_utilization"},
		{1125,"tex_sm_tex_utilization"},
		{1126,"tex_sm_utilization"},
		{1127,"texture_load_requests"},
		{1128,"warp_execution_efficiency"},
		{1129,"warp_nonpred_execution_efficiency"},
	};
}